### ISSUE TITLE
so cannot load

### ISSUE THREAD

**Issue by bjzhou** [cmzy/ZHookLib#1]
01-04 07:41:45.335: W/System.err(2611): java.lang.NoSuchMethodError: dvmIsPrimitiveClassComp not found in libdvm.so
01-04 07:41:45.336: W/System.err(2611):     at com.morgoo.hook.NativeHelper.nativeHe(Native Method)
01-04 07:41:45.336: W/System.err(2611):     at com.morgoo.hook.NativeHelper.<clinit>(NativeHelper.java:22)
01-04 07:41:45.336: W/System.err(2611):     at com.morgoo.hook.zhook.ZHook.hookMethod(ZHook.java:179)
01-04 07:41:45.336: W/System.err(2611):     at com.morgoo.hook.zhook.ZHook.hookAllConstructors(ZHook.java:225)
01-04 07:41:45.336: W/System.err(2611):     at com.morgoo.myjavahook.HookTest.main(HookTest.java:87)
01-04 07:41:45.336: W/System.err(2611):     at com.morgoo.myjavahook.MainActivity.onCreate(MainActivity.java:20)
01-04 07:41:45.336: W/System.err(2611):     at android.app.Activity.performCreate(Activity.java:5393)
01-04 07:41:45.336: W/System.err(2611):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101)
01-04 07:41:45.336: W/System.err(2611):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2501)
01-04 07:41:45.336: W/System.err(2611):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2589)
01-04 07:41:45.337: W/System.err(2611):     at android.app.ActivityThread.access$800(ActivityThread.java:169)
01-04 07:41:45.337: W/System.err(2611):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1513)
01-04 07:41:45.337: W/System.err(2611):     at android.os.Handler.dispatchMessage(Handler.java:110)
01-04 07:41:45.337: W/System.err(2611):     at android.os.Looper.loop(Looper.java:193)
01-04 07:41:45.337: W/System.err(2611):     at android.app.ActivityThread.main(ActivityThread.java:5521)
01-04 07:41:45.337: W/System.err(2611):     at java.lang.reflect.Method.invokeNative(Native Method)
01-04 07:41:45.337: W/System.err(2611):     at java.lang.reflect.Method.invoke(Method.java:515)
01-04 07:41:45.337: W/System.err(2611):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
01-04 07:41:45.337: W/System.err(2611):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:653)
01-04 07:41:45.338: W/System.err(2611):     at dalvik.system.NativeStart.main(Native Method)

**Comment by cmzy** [comment]
Hello,can you send your phone model,os version,and /system/lib/libdvm.so file to me?

**Comment by bjzhou** [comment]
MTK6582, kitkat, [libdvm.so](https://github.com/bjzhou/direct-links/raw/master/libdvm.so), maybe MTK device is different.

Another question, how to hook another app? I tried failed. It only worked hook self

**Comment by cmzy** [comment]
I has fixed it. plz retry.
